//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSLanguagePhpExtention.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportLocation {
            get {
                return ((string)(this["ExportLocation"]));
            }
            set {
                this["ExportLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"class Language\r\n{\r\n\r\n     const base_language = Languages::{langKey};\r\n\r\n   {translationAll}    public function __construct(Languages $lang = Languages::{langKey})\r\n    {\r\n        Session::delete(\""Language\"");\r\n        Session::set(\""Language\"", $lang);\r\n        $this->loadLanguage($lang->value);\r\n    }\r\n\r\n    private function loadLanguage($langPos)\r\n    {\r\n        $jsonData = file_get_contents(GetDocumentRoot() . '/libs/languages/' . $langPos . '.json');\r\n        $data = json_decode($jsonData, true)[0];\r\n        foreach ($data as $key => $value) {\r\n            self::$$key = $value;\r\n        }\r\n    }\r\n\r\n    public static function GetLanguage()\r\n    {\r\n        return !empty( Session::get(\""Language\"")) ? Session::get(\""Language\""): self::base_language;\r\n    }\r\n\r\n}")]
        public string DefaultClass {
            get {
                return ((string)(this["DefaultClass"]));
            }
            set {
                this["DefaultClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("public static ${dictKey} = \\\"\\\";\\r\\n\\r\\n")]
        public string DefaultTranslation {
            get {
                return ((string)(this["DefaultTranslation"]));
            }
            set {
                this["DefaultTranslation"] = value;
            }
        }
    }
}
